// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddIngredientController from "./add_ingredient_controller"
application.register("add-ingredient", AddIngredientController)

import EditIngredientController from "./edit_ingredient_controller"
application.register("edit-ingredient", EditIngredientController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PurchaseIngredientController from "./purchase_ingredient_controller"
application.register("purchase-ingredient", PurchaseIngredientController)

import SearchRecipesController from "./search_recipes_controller"
application.register("search-recipes", SearchRecipesController)

import ShowFiltersController from "./show_filters_controller"
application.register("show-filters", ShowFiltersController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
